// 초급: 양손. 왼손은 긴 음(근음, 화음), 오른손은 8분음표·점음표·3/4박자·조표 1개까지.
// 모두 저작권이 끝난 곡(전래곡, 1900년 이전 작곡)이다.
export const LEVEL2 = [
  {
    file: 'largo-new-world.musicxml',
    title: '라르고 (신세계 교향곡 2악장)',
    composer: 'A. Dvořák',
    tempo: 60,
    measures: [
      { rh: 'E4:q. G4:e G4:h', lh: 'C3:w' },
      { rh: 'E4:q. D4:e C4:h', lh: 'C3:w' },
      { rh: 'D4:q E4:q G4:q E4:q', lh: 'G2:w' },
      { rh: 'D4:w', lh: 'G2:w' },
      { rh: 'E4:q. G4:e G4:h', lh: 'C3:w' },
      { rh: 'E4:q. D4:e C4:h', lh: 'C3:w' },
      { rh: 'D4:q E4:q D4:q. C4:e', lh: 'G2:w' },
      { rh: 'C4:w', lh: 'C3+E3:w' },
    ],
  },
  {
    file: 'clementine.musicxml',
    title: '클레멘타인 (Oh My Darling, Clementine)',
    composer: '미국 민요',
    tempo: 100,
    time: [3, 4],
    measures: [
      { rh: 'r:h C4:e C4:e', lh: 'r:h.' },
      { rh: 'C4:q. G3:e E4:e E4:e', lh: 'C3:h.' },
      { rh: 'E4:q. C4:e C4:e E4:e', lh: 'C3:h.' },
      { rh: 'G4:q. G4:e F4:e E4:e', lh: 'C3:h.' },
      { rh: 'D4:h D4:e E4:e', lh: 'G2:h.' },
      { rh: 'F4:q. F4:e E4:e D4:e', lh: 'G2:h.' },
      { rh: 'E4:q. C4:e C4:e E4:e', lh: 'C3:h.' },
      { rh: 'D4:q. G3:e B3:e D4:e', lh: 'G2:h.' },
      { rh: 'C4:h.', lh: 'C3+E3:h.' },
    ],
  },
  {
    file: 'brahms-lullaby.musicxml',
    title: '브람스의 자장가 (Wiegenlied)',
    composer: 'J. Brahms',
    tempo: 70,
    time: [3, 4],
    measures: [
      { rh: 'r:h E4:e E4:e', lh: 'r:h.' },
      { rh: 'G4:h E4:e E4:e', lh: 'C3:h.' },
      { rh: 'G4:h E4:e G4:e', lh: 'C3:h.' },
      { rh: 'C5:q B4:q. A4:e', lh: 'F3:h.' },
      { rh: 'A4:q G4:q D4:e E4:e', lh: 'C3:h.' },
      { rh: 'F4:q D4:q D4:e E4:e', lh: 'G2:h.' },
      { rh: 'F4:h D4:e F4:e', lh: 'G2:h.' },
      { rh: 'B4:e A4:e G4:q B4:q', lh: 'G2:h.' },
      { rh: 'C5:h.', lh: 'C3+E3:h.' },
    ],
  },
  {
    file: 'amazing-grace.musicxml',
    title: '놀라운 은혜 (Amazing Grace)',
    composer: '미국 찬송가 선율',
    tempo: 80,
    time: [3, 4],
    measures: [
      { rh: 'r:h G3:q', lh: 'r:h.' },
      { rh: 'C4:h E4:e C4:e', lh: 'C3:h.' },
      { rh: 'E4:h D4:q', lh: 'C3:h.' },
      { rh: 'C4:h A3:q', lh: 'F3:h.' },
      { rh: 'G3:h G3:q', lh: 'C3:h.' },
      { rh: 'C4:h E4:e C4:e', lh: 'C3:h.' },
      { rh: 'E4:h D4:q', lh: 'C3:h.' },
      { rh: 'G4:h.', lh: 'G2:h.' },
      { rh: 'r:h E4:q', lh: 'G2:h.' },
      { rh: 'G4:h E4:e C4:e', lh: 'C3:h.' },
      { rh: 'E4:h D4:q', lh: 'C3:h.' },
      { rh: 'C4:h A3:q', lh: 'F3:h.' },
      { rh: 'G3:h G3:q', lh: 'C3:h.' },
      { rh: 'C4:h E4:e C4:e', lh: 'C3:h.' },
      { rh: 'E4:h D4:q', lh: 'G2:h.' },
      { rh: 'C4:h.', lh: 'C3+E3:h.' },
    ],
  },
  {
    file: 'sakura.musicxml',
    title: '벚꽃 (Sakura Sakura)',
    composer: '일본 민요',
    tempo: 70,
    measures: [
      { rh: 'A4:q A4:q B4:h', lh: 'A2:w' },
      { rh: 'A4:q A4:q B4:h', lh: 'A2:w' },
      { rh: 'A4:q B4:q C5:q B4:q', lh: 'A2:w' },
      { rh: 'A4:q B4:e A4:e F4:h', lh: 'D3:w' },
      { rh: 'E4:q C4:q E4:q F4:q', lh: 'A2:w' },
      { rh: 'E4:q E4:e C4:e B3:h', lh: 'E3:w' },
      { rh: 'A4:q B4:q C5:q B4:q', lh: 'A2:w' },
      { rh: 'A4:q B4:e A4:e F4:h', lh: 'D3:w' },
      { rh: 'E4:q C4:q E4:q F4:q', lh: 'A2:w' },
      { rh: 'E4:q E4:e C4:e B3:h', lh: 'E3:w' },
      { rh: 'A4:q A4:q B4:h', lh: 'A2:w' },
      { rh: 'A4:q A4:q B4:h', lh: 'A2:w' },
      { rh: 'E4:q F4:q B4:e A4:e F4:q', lh: 'D3:w' },
      { rh: 'E4:w', lh: 'E3:w' },
    ],
  },
  {
    file: 'auld-lang-syne.musicxml',
    title: '석별의 정 (Auld Lang Syne)',
    composer: '스코틀랜드 민요',
    tempo: 80,
    key: -1,
    measures: [
      { rh: 'r:h. C4:q', lh: 'r:w' },
      { rh: 'F4:q. F4:e F4:q A4:q', lh: 'F3:w' },
      { rh: 'G4:q. F4:e G4:q A4:q', lh: 'C3:w' },
      { rh: 'F4:q. F4:e A4:q C5:q', lh: 'F3:w' },
      { rh: 'D5:h. D5:q', lh: 'Bb2:w' },
      { rh: 'C5:q. A4:e A4:q F4:q', lh: 'F3:w' },
      { rh: 'G4:q. F4:e G4:q A4:q', lh: 'C3:w' },
      { rh: 'F4:q. D4:e D4:q C4:q', lh: 'Bb2:h C3:h' },
      { rh: 'F4:w', lh: 'F3+A3:w' },
    ],
  },
  {
    file: 'silent-night.musicxml',
    title: '고요한 밤 거룩한 밤 (Silent Night)',
    composer: 'F. X. Gruber',
    tempo: 70,
    time: [3, 4],
    measures: [
      { rh: 'G4:q. A4:e G4:q', lh: 'C3:h.' },
      { rh: 'E4:h.', lh: 'C3:h.' },
      { rh: 'G4:q. A4:e G4:q', lh: 'C3:h.' },
      { rh: 'E4:h.', lh: 'C3:h.' },
      { rh: 'D5:h D5:q', lh: 'G2:h.' },
      { rh: 'B4:h.', lh: 'G2:h.' },
      { rh: 'C5:h C5:q', lh: 'C3:h.' },
      { rh: 'G4:h.', lh: 'C3:h.' },
      { rh: 'A4:h A4:q', lh: 'F3:h.' },
      { rh: 'C5:q. B4:e A4:q', lh: 'F3:h.' },
      { rh: 'G4:q. A4:e G4:q', lh: 'C3:h.' },
      { rh: 'E4:h.', lh: 'C3:h.' },
      { rh: 'A4:h A4:q', lh: 'F3:h.' },
      { rh: 'C5:q. B4:e A4:q', lh: 'F3:h.' },
      { rh: 'G4:q. A4:e G4:q', lh: 'C3:h.' },
      { rh: 'E4:h.', lh: 'C3:h.' },
      { rh: 'D5:h D5:q', lh: 'G2:h.' },
      { rh: 'F5:q. D5:e B4:q', lh: 'G2:h.' },
      { rh: 'C5:h.', lh: 'C3:h.' },
      { rh: 'E5:h.', lh: 'C3:h.' },
      { rh: 'C5:q. G4:e E4:q', lh: 'C3:h.' },
      { rh: 'G4:q. F4:e D4:q', lh: 'G2:h.' },
      { rh: 'C4:h.', lh: 'C3+E3:h.' },
    ],
  },
  {
    file: 'joy-to-the-world.musicxml',
    title: '기쁘다 구주 오셨네 (Joy to the World)',
    composer: 'L. Mason 편곡 (G. F. Handel 풍)',
    tempo: 90,
    measures: [
      { rh: 'C5:h B4:q. A4:e', lh: 'C3:w' },
      { rh: 'G4:h. F4:q', lh: 'C3:w' },
      { rh: 'E4:h D4:h', lh: 'G2:w' },
      { rh: 'C4:h. G4:q', lh: 'C3:w' },
      { rh: 'A4:h. A4:q', lh: 'F3:w' },
      { rh: 'B4:h. B4:q', lh: 'G3:w' },
      { rh: 'C5:h. C5:q', lh: 'C3:w' },
      { rh: 'C5:q B4:q A4:q G4:q', lh: 'C3:w' },
      { rh: 'G4:q. F4:e E4:q C5:q', lh: 'C3:w' },
      { rh: 'C5:q B4:q A4:q G4:q', lh: 'C3:w' },
      { rh: 'G4:q. F4:e E4:q E4:q', lh: 'C3:w' },
      { rh: 'E4:q E4:q E4:q E4:e F4:e', lh: 'C3:w' },
      { rh: 'G4:h. F4:e E4:e', lh: 'C3:w' },
      { rh: 'D4:q D4:q D4:q D4:e E4:e', lh: 'G2:w' },
      { rh: 'F4:h. E4:e D4:e', lh: 'G2:w' },
      { rh: 'C4:q C5:h A4:q', lh: 'C3:h F3:h' },
      { rh: 'G4:q. F4:e E4:q F4:q', lh: 'C3:w' },
      { rh: 'E4:h D4:h', lh: 'G2:w' },
      { rh: 'C4:w', lh: 'C3+E3:w' },
    ],
  },
  {
    file: 'deck-the-halls.musicxml',
    title: '덱 더 홀스 (Deck the Halls)',
    composer: '웨일스 민요',
    tempo: 110,
    measures: [
      { rh: 'G4:q. F4:e E4:q D4:q', lh: 'C3:w' },
      { rh: 'C4:q D4:q E4:q C4:q', lh: 'C3:w' },
      { rh: 'D4:e E4:e F4:e D4:e E4:q. D4:e', lh: 'G2:h C3:h' },
      { rh: 'C4:q B3:q C4:h', lh: 'G2:h C3:h' },
      { rh: 'G4:q. F4:e E4:q D4:q', lh: 'C3:w' },
      { rh: 'C4:q D4:q E4:q C4:q', lh: 'C3:w' },
      { rh: 'D4:e E4:e F4:e D4:e E4:q. D4:e', lh: 'G2:h C3:h' },
      { rh: 'C4:q B3:q C4:h', lh: 'G2:h C3:h' },
      { rh: 'D4:q. E4:e F4:q D4:q', lh: 'G2:w' },
      { rh: 'E4:q. F4:e G4:q D4:q', lh: 'C3:h G2:h' },
      { rh: 'E4:e F4:e G4:q A4:e B4:e C5:q', lh: 'C3:w' },
      { rh: 'B4:q A4:q G4:h', lh: 'D3:h G2:h' },
      { rh: 'G4:q. F4:e E4:q D4:q', lh: 'C3:w' },
      { rh: 'C4:q D4:q E4:q C4:q', lh: 'C3:w' },
      { rh: 'A4:e A4:e A4:e A4:e G4:q. F4:e', lh: 'F3:h C3:h' },
      { rh: 'E4:q D4:q C4:h', lh: 'G2:h C3:h' },
    ],
  },
  {
    file: 'we-wish-you.musicxml',
    title: '우리 모두 메리 크리스마스 (We Wish You a Merry Christmas)',
    composer: '영국 캐럴',
    tempo: 110,
    key: -1,
    time: [3, 4],
    measures: [
      { rh: 'r:h C4:q', lh: 'r:h.' },
      { rh: 'F4:q F4:e G4:e F4:e E4:e', lh: 'F3:h.' },
      { rh: 'D4:q D4:q D4:q', lh: 'Bb2:h.' },
      { rh: 'G4:q G4:e A4:e G4:e F4:e', lh: 'C3:h.' },
      { rh: 'E4:q C4:q C4:q', lh: 'C3:h.' },
      { rh: 'A4:q A4:e Bb4:e A4:e G4:e', lh: 'D3:h.' },
      { rh: 'F4:q D4:q C4:e C4:e', lh: 'Bb2:h.' },
      { rh: 'D4:q G4:q E4:q', lh: 'C3:h.' },
      { rh: 'F4:h.', lh: 'F3+A3:h.' },
    ],
  },
].map((s) => ({ ...s, level: 2 }));
