// 입문: 오른손 위주, 4분·2분·온음표, 도 자리(C4~G4) 중심. 저작권이 끝난 전래곡과 직접 만든 연습곡만 넣는다.
const R = 'r:w';
const R3 = 'r:h.';
const rh = (lines, rest = R) => lines.map((l) => ({ rh: l, lh: rest }));

/** 직접 만든 연습곡 (저작권 없음) */
const ETUDE = 'SheetMusic 연습곡';

export const LEVEL1 = [
  // ── 연습곡 ──
  {
    file: 'etude-rh-steps.musicxml',
    title: '연습곡: 오른손 계단',
    composer: ETUDE,
    tempo: 80,
    measures: rh(['C4:q D4:q E4:q F4:q', 'G4:h G4:h', 'G4:q F4:q E4:q D4:q', 'C4:h C4:h', 'C4:q D4:q E4:q F4:q', 'G4:q F4:q E4:q D4:q', 'E4:q D4:q E4:q D4:q', 'C4:w']),
  },
  {
    file: 'etude-down-steps.musicxml',
    title: '연습곡: 내려가는 계단',
    composer: ETUDE,
    tempo: 80,
    measures: rh(['G4:q F4:q E4:q D4:q', 'C4:w', 'A4:q G4:q F4:q E4:q', 'D4:w', 'G4:q F4:q E4:q D4:q', 'E4:q D4:q C4:q D4:q', 'E4:h D4:h', 'C4:w']),
  },
  {
    file: 'etude-lh-steps.musicxml',
    title: '연습곡: 왼손 계단',
    composer: ETUDE,
    tempo: 80,
    measures: ['C3:q D3:q E3:q F3:q', 'G3:h G3:h', 'G3:q F3:q E3:q D3:q', 'C3:h C3:h', 'C3:q E3:q G3:q E3:q', 'F3:q D3:q G3:h', 'E3:q D3:q E3:q D3:q', 'C3:w'].map(
      (l) => ({ rh: R, lh: l }),
    ),
  },
  {
    file: 'etude-thirds.musicxml',
    title: '연습곡: 한 칸 건너뛰기',
    composer: ETUDE,
    tempo: 80,
    measures: rh(['C4:q E4:q D4:q F4:q', 'E4:q G4:q F4:h', 'G4:q E4:q F4:q D4:q', 'E4:q C4:q D4:h', 'C4:q E4:q G4:h', 'G4:q E4:q C4:h', 'D4:q F4:q E4:q D4:q', 'C4:w']),
  },
  {
    file: 'etude-echo.musicxml',
    title: '연습곡: 메아리 (양손 번갈아)',
    composer: ETUDE,
    tempo: 80,
    measures: [
      { rh: 'C4:q D4:q E4:h', lh: R },
      { rh: R, lh: 'C3:q D3:q E3:h' },
      { rh: 'E4:q F4:q G4:h', lh: R },
      { rh: R, lh: 'E3:q F3:q G3:h' },
      { rh: 'G4:q F4:q E4:q D4:q', lh: R },
      { rh: R, lh: 'G3:q F3:q E3:q D3:q' },
      { rh: 'E4:q D4:q C4:h', lh: R },
      { rh: R, lh: 'E3:q D3:q C3:h' },
    ],
  },
  {
    file: 'etude-rests.musicxml',
    title: '연습곡: 쉼표 놀이',
    composer: ETUDE,
    tempo: 90,
    measures: rh(['C4:q r:q C4:q r:q', 'D4:q r:q D4:q r:q', 'E4:q F4:q G4:q r:q', 'G4:h r:h', 'G4:q r:q G4:q r:q', 'F4:q r:q F4:q r:q', 'E4:q D4:q C4:q r:q', 'C4:w']),
  },
  {
    file: 'etude-long-notes.musicxml',
    title: '연습곡: 긴 음 세기',
    composer: ETUDE,
    tempo: 90,
    measures: rh(['C4:h. D4:q', 'E4:w', 'E4:h. F4:q', 'G4:w', 'G4:h. F4:q', 'E4:h D4:h', 'D4:h. E4:q', 'C4:w']),
  },
  {
    file: 'etude-march.musicxml',
    title: '연습곡: 작은 행진곡',
    composer: ETUDE,
    tempo: 100,
    measures: rh(['C4:q E4:q G4:q E4:q', 'F4:q D4:q G4:h', 'E4:q C4:q F4:q D4:q', 'E4:q D4:q C4:h', 'G4:q G4:q E4:q E4:q', 'F4:q F4:q D4:q D4:q', 'E4:q G4:q D4:q G4:q', 'C4:w']),
  },
  {
    file: 'etude-waltz.musicxml',
    title: '연습곡: 첫 왈츠 (3/4박자)',
    composer: ETUDE,
    tempo: 100,
    time: [3, 4],
    measures: rh(['C4:q E4:q G4:q', 'G4:h.', 'F4:q E4:q D4:q', 'D4:h.', 'D4:q F4:q A4:q', 'A4:h.', 'G4:q E4:q D4:q', 'C4:h.'], R3),
  },
  {
    file: 'etude-eighths.musicxml',
    title: '연습곡: 8분음표 산책',
    composer: ETUDE,
    tempo: 80,
    measures: rh([
      'C4:e D4:e E4:e C4:e E4:h',
      'D4:e E4:e F4:e D4:e F4:h',
      'E4:e F4:e G4:e E4:e G4:h',
      'G4:e F4:e E4:e D4:e C4:h',
      'C4:e E4:e G4:e E4:e C4:h',
      'D4:e F4:e A4:e F4:e D4:h',
      'E4:e G4:e F4:e D4:e E4:q D4:q',
      'C4:w',
    ]),
  },
  {
    file: 'etude-g-position.musicxml',
    title: '연습곡: 솔 자리 노래',
    composer: ETUDE,
    tempo: 90,
    measures: rh(['G4:q A4:q B4:q C5:q', 'D5:h D5:h', 'C5:q B4:q A4:q G4:q', 'A4:w', 'G4:q A4:q B4:q C5:q', 'D5:q C5:q B4:q A4:q', 'B4:q A4:q G4:q A4:q', 'G4:w']),
  },
  {
    file: 'etude-black-key.musicxml',
    title: '연습곡: 첫 검은 건반 (파#)',
    composer: ETUDE,
    tempo: 90,
    key: 1,
    measures: rh(['G4:q A4:q B4:q A4:q', 'G4:q F#4:q G4:h', 'A4:q B4:q C5:q B4:q', 'A4:q G4:q A4:h', 'B4:q A4:q G4:q F#4:q', 'E4:q F#4:q G4:h', 'A4:q F#4:q D4:q F#4:q', 'G4:w']),
  },
  {
    file: 'etude-hands-together.musicxml',
    title: '연습곡: 양손 함께 (도와 솔)',
    composer: ETUDE,
    tempo: 80,
    measures: [
      { rh: 'C4:q D4:q E4:q C4:q', lh: 'C3:w' },
      { rh: 'D4:q E4:q F4:q D4:q', lh: 'G2:w' },
      { rh: 'E4:q F4:q G4:q E4:q', lh: 'C3:w' },
      { rh: 'D4:w', lh: 'G2:w' },
      { rh: 'E4:q G4:q E4:q C4:q', lh: 'C3:w' },
      { rh: 'D4:q F4:q D4:q B3:q', lh: 'G2:w' },
      { rh: 'C4:q E4:q D4:q B3:q', lh: 'C3:h G2:h' },
      { rh: 'C4:w', lh: 'C3:w' },
    ],
  },
  {
    file: 'etude-lh-accompany.musicxml',
    title: '연습곡: 왼손 반주 (도-솔)',
    composer: ETUDE,
    tempo: 80,
    measures: [
      { rh: 'E4:h D4:h', lh: 'C3:h G3:h' },
      { rh: 'C4:w', lh: 'C3:h G3:h' },
      { rh: 'D4:h E4:h', lh: 'G2:h G3:h' },
      { rh: 'D4:w', lh: 'G2:h G3:h' },
      { rh: 'E4:h F4:h', lh: 'C3:h G3:h' },
      { rh: 'G4:w', lh: 'C3:h G3:h' },
      { rh: 'F4:h D4:h', lh: 'G2:h G3:h' },
      { rh: 'C4:w', lh: 'C3:w' },
    ],
  },

  // ── 전래곡·동요 (저작권 만료) ──
  {
    file: 'hot-cross-buns.musicxml',
    title: '핫 크로스 번 (Hot Cross Buns)',
    composer: '영국 전래동요',
    tempo: 90,
    measures: rh([
      'E4:q D4:q C4:h',
      'E4:q D4:q C4:h',
      'C4:e C4:e C4:e C4:e D4:e D4:e D4:e D4:e',
      'E4:q D4:q C4:h',
      'E4:q D4:q C4:h',
      'E4:q D4:q C4:h',
      'C4:e C4:e C4:e C4:e D4:e D4:e D4:e D4:e',
      'E4:q D4:q C4:h',
    ]),
  },
  {
    file: 'alle-meine-entchen.musicxml',
    title: '모든 오리들 (Alle meine Entchen)',
    composer: '독일 민요',
    tempo: 90,
    measures: rh(['C4:q D4:q E4:q F4:q', 'G4:h G4:h', 'A4:q A4:q A4:q A4:q', 'G4:w', 'A4:q A4:q A4:q A4:q', 'G4:w', 'F4:q F4:q F4:q F4:q', 'E4:h E4:h', 'D4:q D4:q D4:q D4:q', 'C4:w']),
  },
  {
    file: 'aunt-rhody.musicxml',
    title: '로디 아줌마 (Go Tell Aunt Rhody)',
    composer: '미국 민요',
    tempo: 90,
    measures: rh(['E4:h E4:q D4:q', 'C4:h C4:h', 'D4:h D4:q F4:q', 'E4:q D4:q C4:h', 'G4:h G4:q F4:q', 'E4:h E4:h', 'D4:q C4:q D4:q E4:q', 'C4:w']),
  },
  {
    file: 'au-clair-de-la-lune.musicxml',
    title: '달빛 아래서 (Au clair de la lune)',
    composer: '프랑스 민요',
    tempo: 90,
    measures: rh([
      'C4:q C4:q C4:q D4:q',
      'E4:h D4:h',
      'C4:q E4:q D4:q D4:q',
      'C4:w',
      'C4:q C4:q C4:q D4:q',
      'E4:h D4:h',
      'C4:q E4:q D4:q D4:q',
      'C4:w',
      'D4:q D4:q D4:q D4:q',
      'A3:h A3:h',
      'D4:q C4:q B3:q A3:q',
      'G3:w',
      'C4:q C4:q C4:q D4:q',
      'E4:h D4:h',
      'C4:q E4:q D4:q D4:q',
      'C4:w',
    ]),
  },
  {
    file: 'london-bridge.musicxml',
    title: '런던 다리 (London Bridge)',
    composer: '영국 전래동요',
    tempo: 100,
    measures: rh(['G4:q. A4:e G4:q F4:q', 'E4:q F4:q G4:h', 'D4:q E4:q F4:h', 'E4:q F4:q G4:h', 'G4:q. A4:e G4:q F4:q', 'E4:q F4:q G4:h', 'D4:h G4:h', 'E4:q C4:h.']),
  },
  {
    file: 'frere-jacques.musicxml',
    title: '프레르 자크 (Frère Jacques)',
    composer: '프랑스 민요',
    tempo: 100,
    measures: rh([
      'C4:q D4:q E4:q C4:q',
      'C4:q D4:q E4:q C4:q',
      'E4:q F4:q G4:h',
      'E4:q F4:q G4:h',
      'G4:e A4:e G4:e F4:e E4:q C4:q',
      'G4:e A4:e G4:e F4:e E4:q C4:q',
      'C4:q G3:q C4:h',
      'C4:q G3:q C4:h',
    ]),
  },
  {
    file: 'old-macdonald.musicxml',
    title: '맥도날드 할아버지 (Old MacDonald)',
    composer: '미국 동요',
    tempo: 100,
    measures: rh(['C4:q C4:q C4:q G3:q', 'A3:q A3:q G3:h', 'E4:q E4:q D4:q D4:q', 'C4:h. G3:q', 'C4:q C4:q C4:q G3:q', 'A3:q A3:q G3:h', 'E4:q E4:q D4:q D4:q', 'C4:w']),
  },
  {
    file: 'yankee-doodle.musicxml',
    title: '양키 두들 (Yankee Doodle)',
    composer: '미국 민요',
    tempo: 110,
    measures: rh(['C4:q C4:q D4:q E4:q', 'C4:q E4:q D4:q G3:q', 'C4:q C4:q D4:q E4:q', 'C4:h B3:h', 'C4:q C4:q D4:q E4:q', 'F4:q E4:q D4:q C4:q', 'B3:q G3:q A3:q B3:q', 'C4:h C4:h']),
  },
  {
    file: 'this-old-man.musicxml',
    title: '이 할아버지 (This Old Man)',
    composer: '영국 동요',
    tempo: 100,
    measures: rh([
      'G4:q E4:q G4:h',
      'G4:q E4:q G4:h',
      'A4:q G4:q F4:q E4:q',
      'D4:q E4:q F4:h',
      'E4:e F4:e G4:q C4:q C4:e C4:e',
      'C4:e D4:e E4:e F4:e G4:h',
      'G4:q D4:q D4:q F4:q',
      'E4:q D4:q C4:h',
    ]),
  },
  {
    file: 'augustin.musicxml',
    title: '오 사랑스런 아우구스틴 (O du lieber Augustin)',
    composer: '오스트리아 민요',
    tempo: 110,
    time: [3, 4],
    measures: rh(
      ['G4:q. A4:e G4:q', 'F4:q E4:q F4:q', 'G4:q C4:q C4:q', 'D4:q G3:q G3:q', 'E4:q C4:q C4:q', 'G4:q. A4:e G4:q', 'F4:q E4:q F4:q', 'G4:q C4:q C4:q', 'D4:q G3:q E4:q', 'C4:h.'],
      R3,
    ),
  },
  {
    file: 'row-your-boat.musicxml',
    title: '노를 저어라 (Row, Row, Row Your Boat)',
    composer: '미국 동요',
    tempo: 100,
    time: [6, 8],
    measures: rh(
      ['C4:q. C4:q.', 'C4:q D4:e E4:q.', 'E4:q D4:e E4:q F4:e', 'G4:h.', 'C5:e C5:e C5:e G4:e G4:e G4:e', 'E4:e E4:e E4:e C4:e C4:e C4:e', 'G4:q F4:e E4:q D4:e', 'C4:h.'],
      R3,
    ),
  },
  {
    file: 'three-blind-mice.musicxml',
    title: '세 마리 눈먼 쥐 (Three Blind Mice)',
    composer: '영국 동요',
    tempo: 100,
    time: [6, 8],
    measures: rh(
      [
        'E4:q. D4:q.',
        'C4:h.',
        'E4:q. D4:q.',
        'C4:h.',
        'G4:q F4:e F4:q.',
        'E4:h.',
        'G4:q F4:e F4:q.',
        'E4:h.',
        'G4:e C5:e C5:e B4:e A4:e B4:e',
        'C5:q G4:e G4:q.',
        'G4:e C5:e C5:e B4:e A4:e B4:e',
        'C5:q G4:e G4:q.',
        'G4:e C5:e C5:e C5:e B4:e A4:e',
        'B4:e C5:e G4:e G4:e G4:e F4:e',
        'E4:q. D4:q.',
        'C4:h.',
      ],
      R3,
    ),
  },
  {
    file: 'itsy-bitsy-spider.musicxml',
    title: '거미가 줄을 타고 (Itsy Bitsy Spider)',
    composer: '미국 동요',
    tempo: 100,
    time: [6, 8],
    measures: rh(
      [
        'r:q. r:q G3:e',
        'C4:q C4:e C4:q D4:e',
        'E4:q. E4:q E4:e',
        'D4:q C4:e D4:q E4:e',
        'C4:h.',
        'E4:q. E4:q F4:e',
        'G4:h.',
        'G4:q F4:e E4:q F4:e',
        'G4:q. E4:q.',
        'C4:q. C4:q D4:e',
        'E4:h.',
        'E4:q D4:e C4:q D4:e',
        'E4:q. C4:e G3:e G3:e',
        'C4:q C4:e C4:q D4:e',
        'E4:q. E4:q E4:e',
        'D4:q C4:e D4:q E4:e',
        'C4:h.',
      ],
      R3,
    ),
  },
  {
    file: 'oh-susanna.musicxml',
    title: '오 수재너 (Oh! Susanna)',
    composer: 'S. Foster',
    tempo: 100,
    measures: rh([
      'r:h. C4:e D4:e',
      'E4:q G4:q G4:q. A4:e',
      'G4:q E4:q C4:q. D4:e',
      'E4:q E4:q D4:q C4:q',
      'D4:h. C4:e D4:e',
      'E4:q G4:q G4:q. A4:e',
      'G4:q E4:q C4:q. D4:e',
      'E4:q E4:q D4:q D4:q',
      'C4:w',
    ]),
  },
  {
    file: 'jingle-bells-verse.musicxml',
    title: '징글벨 (1절)',
    composer: 'J. Pierpont',
    tempo: 110,
    measures: rh([
      'G3:q E4:q D4:q C4:q',
      'G3:h. G3:e G3:e',
      'G3:q E4:q D4:q C4:q',
      'A3:w',
      'A3:q F4:q E4:q D4:q',
      'B3:w',
      'G4:q G4:q F4:q D4:q',
      'E4:w',
      'G3:q E4:q D4:q C4:q',
      'G3:w',
      'G3:q E4:q D4:q C4:q',
      'A3:h. A3:q',
      'A3:q F4:q E4:q D4:q',
      'G4:q G4:q G4:q G4:q',
      'A4:q G4:q F4:q D4:q',
      'C4:w',
    ]),
  },
  {
    file: 'when-the-saints.musicxml',
    title: '성자의 행진 (When the Saints Go Marching In)',
    composer: '미국 흑인영가',
    tempo: 110,
    measures: rh([
      'r:q C4:q E4:q F4:q',
      'G4:w',
      'r:q C4:q E4:q F4:q',
      'G4:w',
      'r:q C4:q E4:q F4:q',
      'G4:h E4:h',
      'C4:h E4:h',
      'D4:w',
      'r:q E4:q E4:q D4:q',
      'C4:h. C4:q',
      'E4:h G4:h',
      'G4:q F4:h.',
      'r:q E4:q F4:q G4:q',
      'E4:h C4:h',
      'D4:w',
      'C4:w',
    ]),
  },
].map((s) => ({ ...s, level: 1 }));
